import type { Locale } from "@/lib/i18n";

const assets = {
  hero: "/assets/editorial/hero-bananas-v2.png",
  market: "/assets/editorial/central-asia-market-v2.png",
  quality: "/assets/editorial/origin-quality-v2.png",
  partnership: "/assets/editorial/wholesale-partnership-v1.png",
  inspection: "/assets/editorial/banana-quality-inspection-v1.png",
  ripening: "/assets/editorial/banana-ripening-stages-v1.png",
  product: "/assets/brand/good-garden-crate.jpeg",
  package: "/assets/brand/good-garden-packaging.jpeg",
  ecuador: "/assets/origin/ecuador-field-v2.png",
  philippines: "/assets/origin/philippines-field-v2.png",
  mekong: "/assets/origin/mekong-origins-v2.png",
  guangxi: "/assets/origin/guangxi-field-v2.png",
};

export const cleanCopy = {
  en: {
    nav: { about: "Company", products: "Bananas", supply: "Origins", quality: "Quality", news: "Buyer guide", contact: "Contact" },
    common: { home: "Home", learn: "Learn more", product: "View our banana", contact: "Request a wholesale programme", current: "Current market focus" },
    footer: { line: "Premium bananas for Central Asia.", note: "GOOD GARDEN is a focused international banana brand for importers, distributors, wholesale markets and retail buyers.", explore: "Explore", legal: "© 2026 GOOD GARDEN. All rights reserved." },
    home: {
      seo: { title: "Wholesale Cavendish Bananas for Central Asia | GOOD GARDEN", description: "GOOD GARDEN develops wholesale Cavendish banana programmes from selected origins for importers, distributors and retail buyers across Central Asia." },
      eyebrow: "Premium bananas · Selected origins",
      title: "Better bananas.\nBuilt for Central Asia.",
      intro: "GOOD GARDEN develops banana programmes for importers, distributors, wholesale markets and retail buyers seeking consistent, long-term cooperation across Central Asia.",
      advantages: [
        { title: "Focused on bananas", text: "Product, origin and packing decisions built around one core category." },
        { title: "Six origin options", text: "Ecuador, the Philippines, Cambodia, Vietnam, Laos and Guangxi—availability confirmed by programme." },
        { title: "Built for repeat business", text: "Programmes shaped around the needs of long-term Central Asian buyers." },
      ],
      productEyebrow: "Our product",
      productTitle: "Premium Cavendish",
      productText: "A dependable commercial banana programme with clear specifications, branded presentation and formats for wholesale and retail channels.",
      originsEyebrow: "Where we source",
      originsTitle: "Selected for complementary strengths.",
      originsText: "Our origin portfolio combines established export expertise with responsive Asian supply options.",
      regions: ["Ecuador", "Philippines", "Cambodia", "Vietnam", "Laos", "Guangxi, China"],
      marketEyebrow: "Our market",
      marketTitle: "Central Asia is where we build.",
      marketText: "We are developing long-term relationships in Kazakhstan, Uzbekistan, Kyrgyzstan, Tajikistan and Turkmenistan—while staying open to the next opportunity.",
      buyersEyebrow: "For long-term wholesale partners",
      buyersTitle: "Clear information before every quotation.",
      buyersText: "We first understand how the fruit will be sold, then align the commercial programme around the destination and buyer’s requirements.",
      buyers: [
        { title: "Importers", text: "Origin and order planning for destination-market requirements." },
        { title: "Distributors", text: "Formats and programmes designed for repeat regional demand." },
        { title: "Wholesale markets", text: "Commercial packs and specifications agreed for daily trade." },
        { title: "Retail buyers", text: "Brand presentation and packing details aligned to the channel." },
      ],
      alignTitle: "What we confirm",
      align: ["Destination market", "Expected monthly volume", "Origin and availability", "13 kg or 18.14 kg carton", "Fruit and packing specification", "Required timing and documents"],
      ctaTitle: "Planning a long-term banana programme?",
      ctaText: "Share your destination, expected monthly volume, carton format and preferred start date.",
    },
    about: {
      seo: { title: "Banana Partner for Central Asia | GOOD GARDEN", description: "Meet GOOD GARDEN, a specialist banana brand developing long-term wholesale partnerships across Central Asia." },
      hero: { eyebrow: "Company", title: "Focused on bananas.\nBuilt for partnership.", intro: "We are building a specialised fruit brand around clear sourcing, practical product standards and long-term commercial relationships in Central Asia.", image: assets.partnership, alt: "Representative wholesale banana programme discussion" },
      lead: "GOOD GARDEN is not a general trading catalogue. Bananas are our core business and the product around which we build expertise, brand recognition and dependable partnerships.",
      strengths: [
        { number: "01", title: "Specialist focus", text: "We concentrate our attention on one of the world’s most important fresh-fruit categories." },
        { number: "02", title: "Origin choice", text: "A multi-origin portfolio gives partners more flexibility when planning programmes." },
        { number: "03", title: "Regional understanding", text: "Our commercial work is shaped around Central Asian channels, customers and market conditions." },
      ],
      serviceTitle: "Who we work with",
      serviceText: "Our strongest fit is with professional buyers who plan recurring demand and value direct, practical communication.",
      services: [
        { title: "Fruit importers", text: "Companies coordinating market entry, documentation and destination handling." },
        { title: "Regional distributors", text: "Partners serving several cities, channels or customer groups." },
        { title: "Wholesale operators", text: "Buyers supplying wholesale markets and professional fresh-produce trade." },
        { title: "Retail purchasing teams", text: "Chains and stores that need agreed presentation and packing requirements." },
      ],
      networkTitle: "Origin-side cooperation",
      networkText: "GOOD GARDEN works with China Fruit Dock (中国水果码头) to strengthen origin coordination and front-warehouse support in Southeast Asia. The scope used for each order is confirmed within the specific commercial programme.",
      approachTitle: "How we work",
      approach: ["Understand the buyer’s market", "Match the right origin and format", "Agree practical quality expectations", "Build repeat business through clear communication"],
      noteTitle: "A brand designed to grow",
      noteText: "Bananas are our foundation. Future fruit categories will be added carefully, only when they fit the GOOD GARDEN standard and our partners’ needs.",
    },
    products: {
      seo: { title: "Wholesale Cavendish Bananas | GOOD GARDEN", description: "Explore GOOD GARDEN Cavendish bananas in 13 kg and 18.14 kg formats for import, wholesale, distribution and retail programmes." },
      hero: { eyebrow: "Our banana", title: "One product.\nA precise programme.", intro: "Cavendish bananas for recurring commercial demand, with product and packing requirements confirmed for each origin, destination and order.", image: assets.inspection, alt: "Representative inspection of green Cavendish bananas" },
      lead: "Our product page is intentionally straightforward: the right banana, the right format and an agreed specification for the destination market.",
      details: [
        { label: "Variety", value: "Cavendish" },
        { label: "Positioning", value: "Premium commercial banana" },
        { label: "Channels", value: "Import, wholesale, distribution and retail" },
        { label: "Origins", value: "Selected according to programme" },
      ],
      formatsTitle: "Commercial formats",
      formats: [
        { title: "13 kg net carton", text: "A compact branded format available for selected commercial programmes." },
        { title: "18.14 kg net carton", text: "A widely recognised export format for wholesale programmes." },
        { title: "Agreed presentation", text: "Marking, labels and final artwork are confirmed before the order." },
      ],
      availabilityNote: "Origin, availability, grade, calibration, cluster configuration, loading method and inspection requirements are confirmed for each quotation. We do not publish fixed capacity, lead-time or shelf-life promises without an agreed programme.",
      quotationTitle: "To prepare a useful quotation",
      quotationText: "The more clearly the destination and programme are defined, the more accurately we can match origin, packing and commercial terms.",
      quotationItems: ["Country and destination city", "Buyer type and sales channel", "Expected order or monthly volume", "Preferred 13 kg or 18.14 kg carton", "Target start date", "Required documents or inspection scope"],
      faqTitle: "Wholesale questions",
      faq: [
        { question: "Who is the GOOD GARDEN programme for?", answer: "Professional importers, distributors, wholesale market buyers and retail purchasing teams planning recurring commercial demand." },
        { question: "Which origins can be discussed?", answer: "Ecuador, the Philippines, Cambodia, Vietnam, Laos and Guangxi, China. The final option depends on confirmed availability and the destination programme." },
        { question: "Which carton formats are available?", answer: "13 kg and 18.14 kg net carton formats can be discussed. Final artwork, carton construction and packing details are confirmed in the order." },
        { question: "Are price, minimum order and transit time fixed?", answer: "No. They depend on origin, destination, timing, volume, route and the agreed specification, so they are confirmed in a current quotation." },
        { question: "What should a buyer send first?", answer: "Destination city, buyer type, expected monthly volume, preferred carton, target start date and any document or inspection requirement." },
      ],
      ctaTitle: "Need a banana specification?",
      ctaText: "Share your destination, expected volume, carton preference and timing with our team.",
    },
    detail: {
      seo: { title: "Premium Cavendish Banana Specification | GOOD GARDEN", description: "Commercial reference, packing formats and order-specific specification points for GOOD GARDEN Cavendish bananas." },
      hero: { eyebrow: "Premium Cavendish", title: "Made for recurring demand.", intro: "A commercial banana programme supported by clear product, packing and order requirements.", image: assets.ripening, alt: "Representative Cavendish banana ripening stages", fit: "contain" },
      overview: "Cavendish is the foundation of the GOOD GARDEN range. Because fresh fruit varies by origin, season and destination, final parameters are confirmed in the sales contract or approved order specification.",
      referenceTitle: "Commercial reference",
      reference: [
        { label: "Variety", value: "Cavendish" },
        { label: "Dispatch condition", value: "Green export-stage fruit, as agreed" },
        { label: "Net carton options", value: "13 kg and 18.14 kg" },
        { label: "Origin", value: "Selected for the confirmed programme" },
        { label: "Presentation", value: "GOOD GARDEN or approved order artwork" },
        { label: "Final acceptance", value: "According to the mutually confirmed order specification" },
      ],
      specsTitle: "Points confirmed per order",
      specs: ["Variety and grade", "Finger length and calibration", "Net weight and carton dimensions", "Hands or clusters per carton", "Pallet and loading configuration", "Inspection and document requirements"],
      ripeningTitle: "Plan the destination, not only the departure",
      ripeningText: "Bananas continue to develop after dispatch. Buyers should align arrival condition, local ripening capability, sales channel and expected turnover before the order is confirmed. Exact handling instructions depend on the agreed programme and service providers.",
      noticeTitle: "Fresh produce varies naturally",
      noticeText: "Colour, shape and minor surface variation are natural characteristics of fresh fruit. Commercial acceptance is based on the written specification agreed by both parties, not on a generic website image.",
      ctaTitle: "Request the current programme",
      ctaText: "Tell us your destination, volume, carton preference and target start date so we can discuss the right origin and specification.",
    },
    supply: {
      seo: { title: "Origins | GOOD GARDEN Banana Sourcing", description: "GOOD GARDEN banana sourcing from Ecuador, the Philippines, Cambodia, Vietnam, Laos and Guangxi, China." },
      hero: { eyebrow: "Selected origins", title: "Different regions.\nOne commercial standard.", intro: "We choose origins for the strengths they bring to a specific customer, season and market programme.", image: assets.quality, alt: "Banana grower and quality specialist inspecting fruit" },
      lead: "Multi-origin sourcing is valuable when it creates real options—not complexity. GOOD GARDEN presents each origin clearly so partners can make informed programme decisions.",
      groups: [
        { region: "Latin America", title: "Ecuador", text: "A globally established banana origin with deep export experience and year-round industry production.", image: assets.ecuador, alt: "Representative banana-growing landscape in Ecuador", details: ["Pacific coastal production belt: Guayas, Los Ríos and El Oro", "Established experience in international banana programmes"] },
        { region: "Southeast Asia", title: "Philippines", text: "An export-oriented Cavendish origin with established production, selection, packing and distribution experience.", image: assets.philippines, alt: "Representative Cavendish growing landscape in the Philippines", details: ["Mindanao is the country’s principal export banana base", "Specialised Cavendish production and packing value chain"] },
        { region: "Mainland Southeast Asia", title: "Cambodia · Vietnam · Laos", text: "Three distinct programme options across mainland Southeast Asia; availability and specifications are confirmed separately by country.", image: assets.mekong, alt: "Representative banana-growing settings in Cambodia, Vietnam and Laos", details: ["Cambodia: expanding commercial Cavendish production", "Vietnam and Laos: origin options assessed by season, location and confirmed availability"] },
        { region: "China", title: "Guangxi", text: "One of China’s important banana-producing regions and a practical option for selected programmes connected with China.", image: assets.guangxi, alt: "Representative banana-growing landscape in Guangxi, China", details: ["Nanning and southern Guangxi form an established banana belt", "Final availability and route confirmed per programme"] },
      ],
      matchingTitle: "How we match an origin",
      matchingText: "No single origin is automatically right for every buyer. The final choice follows the commercial and operational requirements of the programme.",
      matchingItems: ["Season and confirmed availability", "Destination and proposed route", "Required carton format", "Fruit and packing specification", "Documentation or inspection scope", "Commercial terms and timing"],
      visualNote: "Origin photographs are representative editorial visuals. Farm, packing and loading information for a specific programme is confirmed separately.",
      mapTitle: "From selected origins to Central Asia",
      mapText: "Our current market development is centred on Kazakhstan, Uzbekistan, Kyrgyzstan, Tajikistan and Turkmenistan. Routes and transit times are confirmed only for a specific quotation.",
    },
    quality: {
      seo: { title: "Quality | GOOD GARDEN", description: "GOOD GARDEN coordinates banana specifications, packing, inspection and market feedback." },
      hero: { eyebrow: "Quality", title: "Clear expectations.\nConsistent decisions.", intro: "Quality begins before packing—with a shared understanding of the product, format, destination and buyer’s requirements.", image: assets.quality, alt: "Banana quality inspection at origin" },
      lead: "We do not present quality as a slogan. For every commercial programme, the important points should be written, reviewed and confirmed.",
      steps: [
        { number: "01", title: "Define", text: "Agree origin, product, packing and acceptance requirements." },
        { number: "02", title: "Check", text: "Coordinate the agreed product, packing and documentation checks." },
        { number: "03", title: "Communicate", text: "Keep information clear before departure and through market arrival." },
        { number: "04", title: "Improve", text: "Use buyer feedback to strengthen the next programme." },
      ],
      deliverablesTitle: "What the buyer can align with us",
      deliverables: [
        { title: "Product specification", text: "The agreed origin, variety, grade, calibration and acceptance points." },
        { title: "Packing and marking", text: "Net weight, carton format, artwork, labels and packing configuration." },
        { title: "Pre-departure information", text: "The documents, photos or inspection scope required for the confirmed order." },
        { title: "Arrival review", text: "Buyer feedback recorded to support the next order and recurring programme." },
      ],
      documentsTitle: "Quality is an agreement, not a generic promise",
      documentsText: "Fresh fruit has natural variation. The applicable product, packing, documentation and acceptance requirements are those written into the mutually confirmed order—not an unverified website claim or certificate logo.",
    },
    news: {
      seo: { title: "Wholesale Banana Buyer Guide | GOOD GARDEN", description: "Practical guidance for preparing Cavendish banana enquiries, specifications and multi-origin wholesale programmes." },
      hero: { eyebrow: "Buyer guide", title: "Better information.\nBetter buying decisions.", intro: "Practical reference points for importers, distributors and wholesale buyers planning a banana programme.", image: assets.ripening, alt: "Representative progression of Cavendish banana ripening stages", fit: "contain" },
      lead: "A professional enquiry is more than a request for a price. These three short guides explain the information that helps both sides prepare a realistic programme.",
      topics: [
        { category: "Enquiry", title: "How to prepare a wholesale banana enquiry", summary: "Start with the destination and route-to-market, then add the information needed to match supply.", points: ["Destination country and city", "Buyer type and sales channel", "Expected order or monthly volume", "Carton preference and target start date"] },
        { category: "Specification", title: "What a commercial banana specification should include", summary: "A useful specification translates quality expectations into points both sides can review.", points: ["Variety, grade and calibration", "Net weight and carton format", "Hands or cluster configuration", "Packing, marking and acceptance scope"] },
        { category: "Programme", title: "What to confirm in a multi-origin programme", summary: "Origin choice should follow availability, destination requirements and the commercial plan—not a country name alone.", points: ["Confirmed availability for the period", "Proposed route and timing", "Required documents or inspection", "Arrival feedback and repeat-order planning"] },
      ],
      ctaTitle: "Have a programme to discuss?",
      ctaText: "Send the destination, monthly volume, carton format and preferred start date to our team.",
    },
    contact: {
      seo: { title: "Contact | GOOD GARDEN", description: "Contact GOOD GARDEN about banana sourcing and market partnerships in Central Asia." },
      hero: { eyebrow: "Contact", title: "Tell us what your market needs.", intro: "For a useful first conversation, share your destination, sales channel, packing preference, expected volume and timing.", image: assets.hero, alt: "Premium Cavendish bananas" },
      formTitle: "Business enquiry",
      peopleTitle: "Commercial contacts",
      officeTitle: "Central Asia office",
      checklistTitle: "Include these details",
      checklist: ["Destination country and city", "Buyer type and sales channel", "Expected monthly volume", "13 kg, 18.14 kg or to be confirmed", "Preferred start date", "Required documents or inspection"],
      form: {
        name: "Your name", company: "Company name", country: "Country / destination city", buyerType: "Buyer type", phone: "Phone / WhatsApp", email: "Work email", volume: "Expected monthly volume", carton: "Carton preference", startDate: "Preferred start date", message: "Additional requirements", select: "Select", buyerOptions: ["Importer", "Distributor", "Wholesale market buyer", "Retail purchasing team", "Other professional buyer"], cartonOptions: ["13 kg net carton", "18.14 kg net carton", "Please recommend"], send: "Request a wholesale programme", sending: "Sending…", success: "Thank you. Your enquiry has been delivered.", error: "We could not deliver the form. Please email or call one of the contacts shown on this page.", privacy: "Your information is used only to respond to this business enquiry.", website: "Website",
      },
    },
  },
  zh: {
    nav: { about: "公司", products: "香蕉产品", supply: "采购产地", quality: "品质", news: "采购指南", contact: "联系" },
    common: { home: "首页", learn: "了解更多", product: "查看香蕉产品", contact: "获取批发合作方案", current: "当前市场重点" },
    footer: { line: "面向中亚市场的精品香蕉。", note: "GOOD GARDEN 是专注香蕉的国际品牌，服务进口商、经销商、批发市场与零售采购团队。", explore: "网站导航", legal: "© 2026 GOOD GARDEN. 保留所有权利。" },
    home: {
      seo: { title: "中亚香蕉批发合作｜GOOD GARDEN 百佳园", description: "GOOD GARDEN 百佳园从精选产地发展卡文迪什香蕉批发项目，面向中亚进口商、经销商、批发市场和零售采购团队。" },
      eyebrow: "精品香蕉 · 精选产地",
      title: "更好的香蕉，\n为中亚市场而来。",
      intro: "GOOD GARDEN 面向中亚进口商、经销商、批发市场和零售采购团队，发展以持续采购和长期合作为目标的香蕉项目。",
      advantages: [
        { title: "专注香蕉", text: "围绕一个核心品类，认真处理产品、产地与包装选择。" },
        { title: "六个产地选择", text: "厄瓜多尔、菲律宾、柬埔寨、越南、老挝和中国广西，具体供应按项目确认。" },
        { title: "面向长期复购", text: "围绕中亚长期批发客户的实际需求设计合作项目。" },
      ],
      productEyebrow: "我们的产品",
      productTitle: "精品卡文迪什香蕉",
      productText: "以清晰规格、统一品牌呈现和批发、零售渠道包装形式为基础的稳定商业香蕉方案。",
      originsEyebrow: "采购产地",
      originsTitle: "不同产地，优势互补。",
      originsText: "我们的产地组合兼顾成熟出口经验与亚洲区域供应的灵活性。",
      regions: ["厄瓜多尔", "菲律宾", "柬埔寨", "越南", "老挝", "中国广西"],
      marketEyebrow: "我们的市场",
      marketTitle: "在中亚，建立长期生意。",
      marketText: "我们正在哈萨克斯坦、乌兹别克斯坦、吉尔吉斯斯坦、塔吉克斯坦和土库曼斯坦发展长期合作，同时关注新的市场机会。",
      buyersEyebrow: "服务长期批发伙伴",
      buyersTitle: "报价之前，先把关键信息说明白。",
      buyersText: "我们先了解香蕉将在哪里、通过什么渠道销售，再围绕目的地和采购方要求匹配商业方案。",
      buyers: [
        { title: "进口商", text: "围绕目的地要求沟通产地选择与采购计划。" },
        { title: "区域经销商", text: "为持续区域需求匹配包装与合作节奏。" },
        { title: "批发市场客户", text: "按日常交易需求确认商业包装与产品规格。" },
        { title: "零售采购团队", text: "根据渠道确认品牌呈现、标识与包装要求。" },
      ],
      alignTitle: "我们会先确认",
      align: ["目的地市场", "预计月采购量", "产地与可用量", "13 kg 或 18.14 kg 纸箱", "果品与包装规格", "时间与所需单证"],
      ctaTitle: "正在规划长期香蕉采购？",
      ctaText: "请告诉我们目的地、预计月采购量、纸箱规格和期望开始时间。",
    },
    about: {
      seo: { title: "中亚香蕉长期合作伙伴｜GOOD GARDEN 百佳园", description: "了解 GOOD GARDEN 百佳园——面向中亚市场发展长期批发合作的专业香蕉品牌。" },
      hero: { eyebrow: "公司", title: "专注香蕉，\n为长期合作而来。", intro: "我们围绕清晰采购、实用产品标准和中亚长期商业关系，建设专业香蕉品牌。", image: assets.partnership, alt: "香蕉批发项目沟通示意场景" },
      lead: "GOOD GARDEN 不是一个品类繁杂的贸易目录。香蕉是我们的核心业务，也是我们建立专业能力、品牌识别和稳定合作的基础。",
      strengths: [
        { number: "01", title: "专精品类", text: "集中精力理解全球最重要的鲜果品类之一。" },
        { number: "02", title: "多产地选择", text: "多元产地组合为合作伙伴规划项目提供更多选择。" },
        { number: "03", title: "中亚市场理解", text: "商业工作围绕中亚渠道、客户与实际市场条件展开。" },
      ],
      serviceTitle: "我们的合作对象",
      serviceText: "最适合我们的，是规划持续采购、重视直接沟通并希望建立长期合作的专业客户。",
      services: [
        { title: "水果进口商", text: "负责市场准入、单证和目的地接货的专业企业。" },
        { title: "区域经销商", text: "覆盖多个城市、渠道或客户群体的销售伙伴。" },
        { title: "批发市场经营者", text: "服务批发市场和专业果蔬贸易的采购客户。" },
        { title: "零售采购团队", text: "需要明确品牌呈现、标识和包装要求的连锁与门店。" },
      ],
      networkTitle: "产地端合作网络",
      networkText: "GOOD GARDEN 与中国水果码头开展合作，加强东南亚产区协调与前置仓支持。每个订单实际使用的合作范围，以具体商业项目确认内容为准。",
      approachTitle: "我们的工作方式",
      approach: ["先理解客户所在市场", "匹配适合的产地与包装", "确认实际品质要求", "通过清晰沟通建立长期复购"],
      noteTitle: "为长期成长而设计",
      noteText: "香蕉是我们的基础。未来只有在符合 GOOD GARDEN 标准和合作伙伴需求时，才会谨慎增加新的水果品类。",
    },
    products: {
      seo: { title: "卡文迪什香蕉批发｜GOOD GARDEN 百佳园", description: "了解 GOOD GARDEN 百佳园 13 kg 与 18.14 kg 卡文迪什香蕉包装，以及面向进口、批发、经销和零售项目的合作信息。" },
      hero: { eyebrow: "香蕉产品", title: "一个产品，\n一套清晰方案。", intro: "面向持续商业需求的卡文迪什香蕉；果品和包装要求按照产地、目的地与具体订单共同确认。", image: assets.inspection, alt: "青色卡文迪什香蕉检查示意场景" },
      lead: "我们的产品页面保持直接：适合的香蕉、适合的包装，以及为目的地市场共同确认的规格。",
      details: [
        { label: "品种", value: "卡文迪什" },
        { label: "定位", value: "精品商业香蕉" },
        { label: "渠道", value: "进口、批发、经销与零售" },
        { label: "产地", value: "根据具体项目选择" },
      ],
      formatsTitle: "商业包装形式",
      formats: [
        { title: "13 kg 净重纸箱", text: "可用于特定商业项目的紧凑型品牌包装。" },
        { title: "18.14 kg 净重纸箱", text: "国际批发项目中常见的出口包装规格。" },
        { title: "确认后的品牌呈现", text: "箱唛、标签与最终图稿在订单前确认。" },
      ],
      availabilityNote: "产地、可用量、等级、果指长度与果径、簇型、装载方式及检验要求均按每次报价确认。在没有具体合作方案前，我们不公开承诺固定产能、交期或货架期。",
      quotationTitle: "为了给出有效报价",
      quotationText: "目的地和采购方案越清晰，我们越能准确匹配产地、包装与商业条件。",
      quotationItems: ["国家与目的地城市", "采购方类型和销售渠道", "预计单次或月采购量", "13 kg 或 18.14 kg 纸箱偏好", "期望开始时间", "所需单证或检验范围"],
      faqTitle: "批发合作常见问题",
      faq: [
        { question: "GOOD GARDEN 主要服务哪些客户？", answer: "面向规划持续商业需求的进口商、经销商、批发市场采购客户和零售采购团队。" },
        { question: "可以沟通哪些采购产地？", answer: "厄瓜多尔、菲律宾、柬埔寨、越南、老挝和中国广西。最终选择取决于已确认可用量与目的地项目。" },
        { question: "有哪些纸箱规格？", answer: "可以沟通 13 kg 与 18.14 kg 净重纸箱。最终图稿、纸箱结构和装箱细节在订单中确认。" },
        { question: "价格、起订量和运输时间固定吗？", answer: "不固定。它们取决于产地、目的地、时间、数量、路线和双方确认的规格，因此以当期报价为准。" },
        { question: "采购方第一次应提供什么？", answer: "目的地城市、采购方类型、预计月采购量、纸箱偏好、计划开始时间，以及单证或检验要求。" },
      ],
      ctaTitle: "需要具体香蕉规格？",
      ctaText: "请告诉我们目的地、预计采购量、纸箱偏好和时间要求。",
    },
    detail: {
      seo: { title: "卡文迪什香蕉商业规格｜GOOD GARDEN 百佳园", description: "查看 GOOD GARDEN 百佳园卡文迪什香蕉商业参考、包装形式与订单确认项目。" },
      hero: { eyebrow: "精品卡文迪什", title: "为持续需求而设计。", intro: "以清晰产品、包装和订单要求为基础的商业香蕉方案。", image: assets.ripening, alt: "卡文迪什香蕉成熟色阶示意", fit: "contain" },
      overview: "卡文迪什香蕉是 GOOD GARDEN 当前产品基础。鲜果会因产地、季节和目的地而存在差异，因此最终参数以销售合同或双方确认的订单规格为准。",
      referenceTitle: "商业参考",
      reference: [
        { label: "品种", value: "卡文迪什" },
        { label: "发运状态", value: "按约定的青熟出口状态" },
        { label: "纸箱净重选择", value: "13 kg 与 18.14 kg" },
        { label: "产地", value: "根据已确认项目选择" },
        { label: "品牌呈现", value: "GOOD GARDEN 或订单批准图稿" },
        { label: "最终验收", value: "以双方确认的订单规格为准" },
      ],
      specsTitle: "每个订单需要确认",
      specs: ["品种与等级", "果指长度与果径", "净重与纸箱尺寸", "每箱把数或簇数", "托盘与装载方式", "检验和文件要求"],
      ripeningTitle: "不仅考虑发运，也要考虑到货销售",
      ripeningText: "香蕉在发运后仍会继续成熟。订单确认前，应结合到货状态、当地催熟条件、销售渠道和预计周转速度进行沟通。具体操作要求取决于已确认的合作方案和相关服务方。",
      noticeTitle: "鲜果存在自然差异",
      noticeText: "颜色、形态与轻微表面差异属于鲜果的自然特征。商业验收以双方书面确认的规格为准，而不是以官网示意图片作为唯一标准。",
      ctaTitle: "获取当前供应方案",
      ctaText: "请提供目的地、采购量、纸箱偏好和计划开始时间，我们将进一步沟通产地与规格。",
    },
    supply: {
      seo: { title: "采购产地 | GOOD GARDEN 百佳园香蕉", description: "GOOD GARDEN 百佳园从厄瓜多尔、菲律宾、柬埔寨、越南、老挝和中国广西采购香蕉。" },
      hero: { eyebrow: "精选产地", title: "不同产区，\n统一商业标准。", intro: "我们根据客户、季节与市场项目，选择能够带来相应优势的产地。", image: assets.quality, alt: "香蕉种植者与品质人员检查果品" },
      lead: "多产地采购的价值是提供真正的选择，而不是增加复杂性。GOOD GARDEN 清楚介绍每个产地，帮助合作伙伴作出项目判断。",
      groups: [
        { region: "南美洲", title: "厄瓜多尔", text: "全球成熟香蕉产区，拥有深厚出口经验，行业全年均有生产。", image: assets.ecuador, alt: "厄瓜多尔香蕉产区代表性景观", details: ["太平洋沿岸核心产区：瓜亚斯、洛斯里奥斯和埃尔奥罗", "长期积累的国际香蕉项目经验"] },
        { region: "东南亚", title: "菲律宾", text: "出口导向的卡文迪什产区，具备成熟的种植、选果、包装和销售经验。", image: assets.philippines, alt: "菲律宾卡文迪什香蕉产区代表性景观", details: ["棉兰老岛是菲律宾主要出口香蕉生产区域", "专业卡文迪什种植与包装产业链"] },
        { region: "东南亚大陆", title: "柬埔寨 · 越南 · 老挝", text: "东南亚大陆三个不同的项目选择，具体供应和规格按国家分别确认。", image: assets.mekong, alt: "柬埔寨、越南和老挝香蕉产区代表性场景", details: ["柬埔寨：持续发展的商业卡文迪什生产", "越南和老挝：根据季节、地点和已确认可用量评估项目"] },
        { region: "中国", title: "广西", text: "中国重要香蕉产区之一，也是与中国相关项目的现实选择。", image: assets.guangxi, alt: "中国广西香蕉产区代表性景观", details: ["南宁及广西南部形成成熟香蕉产业带", "最终可用量与路线按具体项目确认"] },
      ],
      matchingTitle: "如何匹配产地",
      matchingText: "没有一个产地天然适合所有采购方。最终选择需要同时满足商业方案与具体执行条件。",
      matchingItems: ["季节与已确认可用量", "目的地与拟议路线", "所需纸箱规格", "果品与包装要求", "单证或检验范围", "商业条件与时间"],
      visualNote: "产地图为代表性编辑视觉。具体项目对应的基地、包装与装载信息，将在商务沟通中另行确认。",
      mapTitle: "从精选产地到中亚",
      mapText: "我们当前的市场发展重点是哈萨克斯坦、乌兹别克斯坦、吉尔吉斯斯坦、塔吉克斯坦和土库曼斯坦。路线与运输时间只在具体报价中确认。",
    },
    quality: {
      seo: { title: "品质 | GOOD GARDEN 百佳园", description: "GOOD GARDEN 百佳园协同香蕉规格、包装、检验和市场反馈。" },
      hero: { eyebrow: "品质", title: "清晰要求，\n稳定决定。", intro: "品质从包装前开始：双方先清楚理解产品、包装、目的地和采购方要求。", image: assets.quality, alt: "香蕉产地品质检查" },
      lead: "我们不把品质只当作一句口号。每个商业项目的重要标准都应该被写明、核对并确认。",
      steps: [
        { number: "01", title: "定义", text: "确认产地、产品、包装和验收要求。" },
        { number: "02", title: "检查", text: "协调双方认可的果品、包装与文件检查。" },
        { number: "03", title: "沟通", text: "在发运前和进入市场过程中保持信息清晰。" },
        { number: "04", title: "改进", text: "根据采购方反馈持续完善下一批项目。" },
      ],
      deliverablesTitle: "采购方可以与我们确认什么",
      deliverables: [
        { title: "产品规格", text: "双方确认的产地、品种、等级、果指与验收要点。" },
        { title: "包装与标识", text: "净重、纸箱形式、图稿、标签和装箱要求。" },
        { title: "发运前信息", text: "已确认订单所需的文件、照片或检验范围。" },
        { title: "到货复盘", text: "记录采购方反馈，为下一单和持续合作提供参考。" },
      ],
      documentsTitle: "品质是一份双方确认，而不是泛泛承诺",
      documentsText: "鲜果存在自然差异。实际适用的果品、包装、单证与验收要求，以双方确认的订单内容为准，不以未经核实的官网表述或证书标志代替。",
    },
    news: {
      seo: { title: "香蕉批发采购指南｜GOOD GARDEN 百佳园", description: "了解卡文迪什香蕉询价、商业规格和多产地批发项目需要确认的关键信息。" },
      hero: { eyebrow: "采购指南", title: "信息更清楚，\n采购决策更准确。", intro: "为进口商、经销商和批发采购客户准备的实用香蕉项目参考。", image: assets.ripening, alt: "卡文迪什香蕉成熟色阶示意", fit: "contain" },
      lead: "专业询价不只是问一个价格。下面三份简明指南说明哪些信息能帮助双方建立更现实、更有效的合作方案。",
      topics: [
        { category: "询价", title: "如何准备香蕉批发询价", summary: "先说明目的地与销售方式，再补齐匹配供应所需的信息。", points: ["目的地国家和城市", "采购方类型与销售渠道", "预计单次或月采购量", "纸箱偏好与计划开始时间"] },
        { category: "规格", title: "商业香蕉规格应该包含什么", summary: "实用规格会把品质期待转换为双方可以逐项确认的内容。", points: ["品种、等级与果指标准", "净重与纸箱形式", "把数或簇型要求", "包装、标识与验收范围"] },
        { category: "项目", title: "多产地项目需要确认什么", summary: "产地选择应服从可用量、目的地要求和商业计划，而不只是比较国家名称。", points: ["计划周期内的已确认可用量", "拟议路线与时间", "所需单证或检验", "到货反馈与复购计划"] },
      ],
      ctaTitle: "有采购项目需要沟通？",
      ctaText: "请把目的地、月采购量、纸箱规格和计划开始时间发给我们。",
    },
    contact: {
      seo: { title: "联系 | GOOD GARDEN 百佳园", description: "联系 GOOD GARDEN 百佳园，沟通中亚香蕉采购与市场合作。" },
      hero: { eyebrow: "联系", title: "告诉我们，\n你的市场需要什么。", intro: "为了让第一次沟通更有效，请提供目的地、销售渠道、包装偏好、预计数量和时间。", image: assets.hero, alt: "精品卡文迪什香蕉" },
      formTitle: "商务咨询",
      peopleTitle: "商务联系人",
      officeTitle: "中亚办公室",
      checklistTitle: "建议提供这些信息",
      checklist: ["目的地国家和城市", "采购方类型与销售渠道", "预计月采购量", "13 kg、18.14 kg 或待确认", "期望开始时间", "所需单证或检验"],
      form: {
        name: "您的姓名", company: "公司名称", country: "国家 / 目的地城市", buyerType: "采购方类型", phone: "电话 / WhatsApp", email: "工作邮箱", volume: "预计月采购量", carton: "纸箱偏好", startDate: "期望开始时间", message: "其他要求", select: "请选择", buyerOptions: ["进口商", "区域经销商", "批发市场采购", "零售采购团队", "其他专业采购方"], cartonOptions: ["13 kg 净重纸箱", "18.14 kg 净重纸箱", "请推荐"], send: "获取批发合作方案", sending: "正在提交…", success: "感谢联系，您的询价已成功发送。", error: "表单暂时无法送达，请直接通过本页邮箱或电话联系我们。", privacy: "您的信息仅用于回复本次商务咨询。", website: "网站",
      },
    },
  },
  ru: {
    nav: { about: "Компания", products: "Бананы", supply: "Регионы", quality: "Качество", news: "Гид покупателя", contact: "Контакты" },
    common: { home: "Главная", learn: "Подробнее", product: "Наши бананы", contact: "Запросить оптовую программу", current: "Текущий фокус" },
    footer: { line: "Премиальные бананы для Центральной Азии.", note: "GOOD GARDEN — специализированный банановый бренд для импортёров, дистрибьюторов, оптовых рынков и закупщиков ритейла.", explore: "Навигация", legal: "© 2026 GOOD GARDEN. Все права защищены." },
    home: {
      seo: { title: "Бананы Cavendish оптом для Центральной Азии | GOOD GARDEN", description: "GOOD GARDEN развивает оптовые программы Cavendish из избранных регионов для импортёров, дистрибьюторов и ритейла Центральной Азии." },
      eyebrow: "Премиальные бананы · Избранные регионы",
      title: "Лучшие бананы.\nДля Центральной Азии.",
      intro: "GOOD GARDEN развивает банановые программы для импортёров, дистрибьюторов, оптовых рынков и ритейла, ориентированных на стабильное долгосрочное сотрудничество в Центральной Азии.",
      advantages: [
        { title: "Фокус на бананах", text: "Решения по продукту, происхождению и упаковке в одной категории." },
        { title: "Шесть регионов", text: "Эквадор, Филиппины, Камбоджа, Вьетнам, Лаос и Гуанси; доступность подтверждается по программе." },
        { title: "Для повторных закупок", text: "Программы под потребности долгосрочных покупателей Центральной Азии." },
      ],
      productEyebrow: "Наш продукт", productTitle: "Премиальный Cavendish", productText: "Надёжная коммерческая программа с ясной спецификацией, фирменной подачей и форматами для опта и ритейла.",
      originsEyebrow: "Где мы закупаем", originsTitle: "Взаимодополняющие преимущества.", originsText: "Наш портфель объединяет развитую экспортную экспертизу и гибкие азиатские варианты.",
      regions: ["Эквадор", "Филиппины", "Камбоджа", "Вьетнам", "Лаос", "Гуанси, Китай"],
      marketEyebrow: "Наш рынок", marketTitle: "Мы строим бизнес в Центральной Азии.", marketText: "Мы развиваем долгосрочные отношения в Казахстане, Узбекистане, Кыргызстане, Таджикистане и Туркменистане, оставаясь открытыми новым возможностям.",
      buyersEyebrow: "Для долгосрочных оптовых партнёров",
      buyersTitle: "Ясные данные до расчёта предложения.",
      buyersText: "Сначала мы понимаем, где и как будет продаваться товар, затем согласуем программу с учётом рынка назначения и требований покупателя.",
      buyers: [
        { title: "Импортёры", text: "Выбор происхождения и планирование заказа под рынок назначения." },
        { title: "Дистрибьюторы", text: "Форматы и программы для повторного регионального спроса." },
        { title: "Оптовые рынки", text: "Коммерческая упаковка и спецификации для ежедневной торговли." },
        { title: "Закупщики ритейла", text: "Оформление бренда и упаковка с учётом канала продаж." },
      ],
      alignTitle: "Что мы уточняем",
      align: ["Рынок назначения", "Ожидаемый месячный объём", "Происхождение и доступность", "Короб 13 или 18,14 кг", "Спецификацию продукта и упаковки", "Сроки и необходимые документы"],
      ctaTitle: "Планируете долгосрочную закупку бананов?", ctaText: "Укажите рынок назначения, ожидаемый месячный объём, формат коробки и желаемую дату начала.",
    },
    about: {
      seo: { title: "Партнёр по бананам в Центральной Азии | GOOD GARDEN", description: "GOOD GARDEN — специализированный банановый бренд, развивающий долгосрочные оптовые партнёрства в Центральной Азии." },
      hero: { eyebrow: "Компания", title: "Фокус на бананах.\nОснова для партнёрства.", intro: "Мы строим специализированный бренд вокруг понятных закупок, практичных требований к продукту и долгосрочных отношений в Центральной Азии.", image: assets.partnership, alt: "Иллюстрация обсуждения оптовой банановой программы" },
      lead: "GOOD GARDEN — не универсальный торговый каталог. Бананы — наш основной бизнес и основа экспертизы, узнаваемости и надёжных отношений.",
      strengths: [
        { number: "01", title: "Специализация", text: "Мы сосредоточены на одной из важнейших категорий свежих фруктов." },
        { number: "02", title: "Выбор происхождения", text: "Портфель регионов даёт партнёрам больше вариантов для планирования." },
        { number: "03", title: "Понимание региона", text: "Наша работа учитывает каналы, клиентов и условия Центральной Азии." },
      ],
      serviceTitle: "С кем мы работаем",
      serviceText: "Лучше всего нам подходят профессиональные покупатели, которые планируют повторный спрос и ценят прямое, практичное общение.",
      services: [
        { title: "Импортёры фруктов", text: "Компании, координирующие ввоз, документы и работу в стране назначения." },
        { title: "Региональные дистрибьюторы", text: "Партнёры, обслуживающие несколько городов, каналов или групп клиентов." },
        { title: "Операторы оптовых рынков", text: "Покупатели для профессиональной оптовой торговли свежими фруктами." },
        { title: "Закупщики ритейла", text: "Сети и магазины, которым нужны согласованные требования к оформлению и упаковке." },
      ],
      networkTitle: "Сотрудничество в регионах происхождения",
      networkText: "GOOD GARDEN сотрудничает с China Fruit Dock (中国水果码头), усиливая координацию и поддержку передовых складских узлов в Юго-Восточной Азии. Объём участия подтверждается отдельно для каждой коммерческой программы.",
      approachTitle: "Как мы работаем", approach: ["Понимаем рынок покупателя", "Выбираем регион и формат", "Согласуем требования к качеству", "Строим повторный бизнес через ясную связь"],
      noteTitle: "Бренд, готовый расти", noteText: "Бананы — наша основа. Новые фруктовые категории появятся только тогда, когда будут соответствовать стандарту GOOD GARDEN и потребностям партнёров.",
    },
    products: {
      seo: { title: "Бананы Cavendish оптом | GOOD GARDEN", description: "Бананы Cavendish GOOD GARDEN в коробах 13 и 18,14 кг для импорта, опта, дистрибуции и розничных программ." },
      hero: { eyebrow: "Наши бананы", title: "Один продукт.\nТочная программа.", intro: "Cavendish для повторного коммерческого спроса; требования к продукту и упаковке подтверждаются для каждого происхождения, направления и заказа.", image: assets.inspection, alt: "Иллюстрация проверки зелёных бананов Cavendish" },
      lead: "Страница продукта проста: подходящий банан, подходящий формат и согласованная спецификация для рынка назначения.",
      details: [{label:"Сорт",value:"Cavendish"},{label:"Позиционирование",value:"Премиальная коммерческая программа"},{label:"Каналы",value:"Импорт, опт, дистрибуция и ритейл"},{label:"Происхождение",value:"Выбирается для программы"}],
      formatsTitle: "Коммерческие форматы", formats: [{title:"Короб 13 кг нетто",text:"Компактный фирменный формат для отдельных программ."},{title:"Короб 18,14 кг нетто",text:"Распространённый экспортный формат для оптовых программ."},{title:"Согласованное оформление",text:"Маркировка, этикетки и финальный макет утверждаются до заказа."}],
      availabilityNote: "Происхождение, доступность, класс, калибр, конфигурация кластеров, способ загрузки и требования к проверке подтверждаются в каждом предложении. Мы не публикуем фиксированные обещания по объёму, срокам или хранению без согласованной программы.",
      quotationTitle: "Для точного предложения",
      quotationText: "Чем яснее определены направление и программа, тем точнее можно подобрать происхождение, упаковку и коммерческие условия.",
      quotationItems: ["Страна и город назначения", "Тип покупателя и канал продаж", "Объём заказа или в месяц", "Предпочтение 13 или 18,14 кг", "Желаемая дата начала", "Документы или объём проверки"],
      faqTitle: "Вопросы по оптовой программе",
      faq: [
        {question:"Для кого предназначена программа GOOD GARDEN?",answer:"Для профессиональных импортёров, дистрибьюторов, покупателей оптовых рынков и закупщиков ритейла с повторным коммерческим спросом."},
        {question:"Какие регионы можно обсудить?",answer:"Эквадор, Филиппины, Камбоджа, Вьетнам, Лаос и Гуанси, Китай. Финальный вариант зависит от подтверждённой доступности и направления."},
        {question:"Какие форматы коробов доступны?",answer:"Можно обсудить короба 13 и 18,14 кг нетто. Макет, конструкция короба и детали упаковки подтверждаются в заказе."},
        {question:"Цена, минимальный заказ и транзит фиксированы?",answer:"Нет. Они зависят от происхождения, направления, периода, объёма, маршрута и спецификации и подтверждаются в актуальном предложении."},
        {question:"Что покупателю отправить сначала?",answer:"Город назначения, тип покупателя, месячный объём, формат короба, дату начала и требования к документам или проверке."},
      ],
      ctaTitle: "Нужна спецификация?", ctaText: "Сообщите направление, ожидаемый объём, формат короба и желаемые сроки.",
    },
    detail: {
      seo: { title: "Коммерческая спецификация Cavendish | GOOD GARDEN", description: "Коммерческие параметры, упаковка и пункты согласования заказа бананов Cavendish GOOD GARDEN." },
      hero: { eyebrow: "Премиальный Cavendish", title: "Для повторного спроса.", intro: "Коммерческая программа на основе ясных требований к продукту, упаковке и заказу.", image: assets.ripening, alt: "Иллюстрация стадий созревания бананов Cavendish", fit: "contain" },
      overview: "Cavendish — основа ассортимента GOOD GARDEN. Поскольку свежий фрукт зависит от происхождения, сезона и назначения, финальные параметры фиксируются в договоре или согласованной спецификации заказа.",
      referenceTitle: "Коммерческие параметры",
      reference: [
        { label: "Сорт", value: "Cavendish" },
        { label: "Состояние при отправке", value: "Зелёный экспортный фрукт по согласованию" },
        { label: "Вес нетто короба", value: "13 кг и 18,14 кг" },
        { label: "Происхождение", value: "Выбирается для подтверждённой программы" },
        { label: "Оформление", value: "GOOD GARDEN или утверждённый макет заказа" },
        { label: "Приёмка", value: "По взаимно подтверждённой спецификации" },
      ],
      specsTitle: "Что подтверждается в заказе",
      specs: ["Сорт и класс", "Длина и калибр", "Вес и размеры короба", "Количество кистей или кластеров", "Паллетизация и загрузка", "Инспекция и документы"],
      ripeningTitle: "Планируйте не только отправку, но и продажу",
      ripeningText: "Бананы продолжают развиваться после отправки. До подтверждения заказа важно согласовать состояние при прибытии, местные возможности дозаривания, канал продаж и ожидаемую оборачиваемость. Точные инструкции зависят от утверждённой программы и поставщиков услуг.",
      noticeTitle: "Свежий фрукт имеет естественные различия",
      noticeText: "Цвет, форма и небольшие различия поверхности естественны. Коммерческая приёмка основывается на письменной спецификации, согласованной сторонами, а не на общей фотографии на сайте.",
      ctaTitle: "Запросить текущую программу",
      ctaText: "Укажите направление, объём, формат короба и дату начала, чтобы обсудить происхождение и спецификацию.",
    },
    supply: {
      seo: { title: "Регионы происхождения | GOOD GARDEN", description: "Закупки бананов GOOD GARDEN в Эквадоре, на Филиппинах, в Камбодже, Вьетнаме, Лаосе и Гуанси." },
      hero: { eyebrow: "Избранные регионы", title: "Разные регионы.\nОдин коммерческий стандарт.", intro: "Мы выбираем происхождение под сильные стороны конкретного клиента, сезона и рыночной программы.", image: assets.quality, alt: "Производитель и специалист проверяют бананы" },
      lead: "Ценность нескольких регионов — в реальном выборе, а не в сложности. GOOD GARDEN ясно представляет каждый вариант для обоснованных решений.",
      groups: [
        {region:"Латинская Америка",title:"Эквадор",text:"Один из признанных мировых банановых регионов с развитой экспортной практикой и круглогодичным отраслевым производством.",image:assets.ecuador,alt:"Репрезентативный вид бананового региона Эквадора",details:["Тихоокеанский пояс: Гуаяс, Лос-Риос и Эль-Оро","Накопленный опыт международных банановых программ"]},
        {region:"Юго-Восточная Азия",title:"Филиппины",text:"Экспортно-ориентированный регион Cavendish с опытом выращивания, отбора, упаковки и дистрибуции.",image:assets.philippines,alt:"Репрезентативный вид региона Cavendish на Филиппинах",details:["Минданао — основная экспортная банановая база страны","Специализированная цепочка производства и упаковки Cavendish"]},
        {region:"Материковая Юго-Восточная Азия",title:"Камбоджа · Вьетнам · Лаос",text:"Три отдельных варианта программы; доступность и спецификация подтверждаются по каждой стране отдельно.",image:assets.mekong,alt:"Репрезентативные банановые регионы Камбоджи, Вьетнама и Лаоса",details:["Камбоджа: развивающееся коммерческое производство Cavendish","Вьетнам и Лаос: оценка по сезону, локации и подтверждённой доступности"]},
        {region:"Китай",title:"Гуанси",text:"Один из важных банановых регионов Китая и практичный вариант для отдельных программ, связанных с Китаем.",image:assets.guangxi,alt:"Репрезентативный вид бананового региона Гуанси",details:["Наньнин и юг Гуанси формируют развитый банановый пояс","Доступность и маршрут подтверждаются по программе"]},
      ],
      matchingTitle: "Как мы выбираем происхождение",
      matchingText: "Ни один регион не подходит автоматически каждому покупателю. Выбор следует коммерческим и операционным требованиям программы.",
      matchingItems: ["Сезон и подтверждённая доступность", "Направление и предложенный маршрут", "Требуемый формат короба", "Спецификация продукта и упаковки", "Документы или объём проверки", "Коммерческие условия и сроки"],
      visualNote: "Фотографии регионов являются репрезентативными редакционными материалами. Данные конкретной фермы, упаковки и загрузки подтверждаются отдельно.",
      mapTitle: "Из избранных регионов в Центральную Азию", mapText: "Наш текущий фокус — Казахстан, Узбекистан, Кыргызстан, Таджикистан и Туркменистан. Маршрут и транзитное время подтверждаются только для конкретного предложения.",
    },
    quality: {
      seo: { title: "Качество | GOOD GARDEN", description: "GOOD GARDEN координирует спецификации, упаковку, инспекцию и обратную связь." },
      hero: { eyebrow: "Качество", title: "Ясные требования.\nПоследовательные решения.", intro: "Качество начинается до упаковки — с общего понимания продукта, формата, направления и требований покупателя.", image: assets.quality, alt: "Проверка качества бананов" },
      lead: "Мы не используем качество только как лозунг. Важные условия каждой программы должны быть записаны, проверены и подтверждены.",
      steps: [{number:"01",title:"Определить",text:"Согласовать регион, продукт, упаковку и приёмку."},{number:"02",title:"Проверить",text:"Координировать согласованные проверки продукта и документов."},{number:"03",title:"Сообщать",text:"Поддерживать ясную информацию до отправки и прибытия."},{number:"04",title:"Улучшать",text:"Использовать отзыв покупателя в следующей программе."}],
      deliverablesTitle: "Что покупатель может согласовать с нами",
      deliverables: [
        {title:"Спецификация продукта",text:"Согласованные происхождение, сорт, класс, калибр и критерии приёмки."},
        {title:"Упаковка и маркировка",text:"Вес нетто, формат короба, макет, этикетки и конфигурация упаковки."},
        {title:"Информация до отправки",text:"Документы, фото или объём проверки для подтверждённого заказа."},
        {title:"Разбор прибытия",text:"Обратная связь покупателя для следующего заказа и повторной программы."},
      ],
      documentsTitle: "Качество — это договорённость, а не общий лозунг", documentsText: "Свежий фрукт имеет естественные различия. Применимы требования к продукту, упаковке, документам и приёмке, письменно подтверждённые в заказе, а не неподтверждённые заявления или знаки сертификатов на сайте.",
    },
    news: {
      seo: { title: "Гид по оптовой закупке бананов | GOOD GARDEN", description: "Практическое руководство по запросу, спецификации и мульти-региональной оптовой программе бананов Cavendish." },
      hero: { eyebrow: "Гид покупателя", title: "Больше ясности.\nТочнее решения.", intro: "Практические ориентиры для импортёров, дистрибьюторов и оптовых покупателей, планирующих банановую программу.", image: assets.ripening, alt: "Иллюстрация стадий созревания Cavendish", fit: "contain" },
      lead: "Профессиональный запрос — это не только просьба назвать цену. Три кратких руководства объясняют, какие данные помогают подготовить реалистичную программу.",
      topics: [
        {category:"Запрос",title:"Как подготовить оптовый запрос на бананы",summary:"Начните с направления и канала продаж, затем добавьте данные для подбора предложения.",points:["Страна и город назначения","Тип покупателя и канал продаж","Объём заказа или в месяц","Формат короба и дата начала"]},
        {category:"Спецификация",title:"Что включает коммерческая спецификация",summary:"Полезная спецификация переводит ожидания по качеству в пункты, которые можно проверить.",points:["Сорт, класс и калибр","Вес нетто и формат короба","Конфигурация кистей или кластеров","Упаковка, маркировка и приёмка"]},
        {category:"Программа",title:"Что уточнить для нескольких регионов",summary:"Выбор происхождения следует доступности, назначению и коммерческому плану, а не только названию страны.",points:["Доступность в нужный период","Маршрут и сроки","Документы или проверка","Обратная связь и повторный заказ"]},
      ],
      ctaTitle: "Есть программа для обсуждения?", ctaText: "Отправьте направление, месячный объём, формат короба и желаемую дату начала.",
    },
    contact: {
      seo: { title: "Контакты | GOOD GARDEN", description: "Свяжитесь с GOOD GARDEN по закупкам бананов и партнёрству в Центральной Азии." },
      hero: { eyebrow: "Контакты", title: "Расскажите, что нужно вашему рынку.", intro: "Для полезного первого разговора укажите направление, канал, формат, объём и сроки.", image: assets.hero, alt: "Премиальные бананы Cavendish" },
      formTitle: "Коммерческий запрос", peopleTitle: "Контакты", officeTitle: "Офис в Центральной Азии",
      checklistTitle: "Что желательно указать",
      checklist: ["Страна и город назначения", "Тип покупателя и канал", "Ожидаемый месячный объём", "13 кг, 18,14 кг или уточнить", "Желаемая дата начала", "Документы или объём проверки"],
      form: {
        name:"Ваше имя",company:"Компания",country:"Страна / город назначения",buyerType:"Тип покупателя",phone:"Телефон / WhatsApp",email:"Рабочий email",volume:"Ожидаемый месячный объём",carton:"Формат короба",startDate:"Желаемая дата начала",message:"Дополнительные требования",select:"Выберите",buyerOptions:["Импортёр","Дистрибьютор","Покупатель оптового рынка","Закупщик розничной сети","Другой профессиональный покупатель"],cartonOptions:["Короб 13 кг нетто","Короб 18,14 кг нетто","Пожалуйста, порекомендуйте"],send:"Запросить оптовую программу",sending:"Отправка…",success:"Спасибо. Ваш запрос успешно доставлен.",error:"Форму не удалось доставить. Напишите или позвоните по контактам на этой странице.",privacy:"Ваши данные используются только для ответа на этот деловой запрос.",website:"Сайт",
      },
    },
  },
} as const;

export function getCleanCopy(locale: Locale) { return cleanCopy[locale]; }
